server.port=8080
spring.application.name=ecommerce

# Sentry – replace with your actual DSN
sentry.dsn=https://26f68cf33f04f9c2bc2d06a07fe13543@o4511066527956992.ingest.us.sentry.io/4511066885980160
sentry.traces-sample-rate=1.0
sentry.logging.minimum-event-level=info
sentry.logging.minimum-breadcrumb-level=debug
sentry.logs.enabled=true



